# Generated by Django 5.0.2 on 2024-03-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_uuidcategory_legacybook_alter_uuidbook_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="offer",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
