# Generated by Django 5.0.2 on 2024-03-30 10:43

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_book_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cost",
            field=models.GeneratedField(
                db_column="cost",
                db_persist=True,
                expression=django.db.models.expressions.RawSQL(
                    "COALESCE(price, offer)", []
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=10),
            ),
        ),
    ]
